spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/lolx?characterencoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 6000
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2

    #    jedis:
#      pool:
#        # 最大连接数 负值表示没有限制
#        max-active: 100
#        # 连接池最大阻塞等待时间，负值没有限制
#        max-wait: -1
#        # 最大空闲连接
#        max-idle: 8
#        # 最小空闲连接
#        min-idle: 5
    # 连接超时时间
    timeout: 100

mybatis:
  type-aliases-package: com.cx.demo.pojo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    com:
      cx: debug